app_post_new:
    path: /post/new
    defaults: { _controller: AppBundle:Post:new }

app_post_index:
    path: /post/index
    defaults: { _controller: AppBundle:Post:index }

app_categories:
    methods: GET
    path: /categories
    defaults: { _controller: AppBundle:Category:index }
